### ISSUE TITLE
consider naming this repo 'onboarding' instead of 'recruiting'

### ISSUE THREAD

**Issue by Azulinho** [actionjack/so-you-want-to-recruit-a-devops-engineer#2]
Most of the tips and info in this repo is not actually related about recruiting or hiring devops engineers, but mostly about making their onboarding as efficient as possible.
There is a bunch of info out there about how to make your company more attractive to engineers, but not so much about how to make those first days on the job as straight-forward, welcoming, and simple as possible. This is a good collection of tips for that, and I think it would be more valuable if the repo was named after that 'onboarding' process.

**Comment by actionjack** [comment]
Point taken considering that it was the onboarding process that made me write this initially. Thanks a lot
